SstoreClient/Pages/Cart.cshtml.cs
using DTO.AccountDTO;
using DTO.BillItemDTO;
using DTO.CartDTO;
using DTO.CategoryDTO;
using DTO.ProductDTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Runtime.Intrinsics.Arm;
using System.Text;
using System.Text.Json;

namespace SstoreClient.Pages
{
    public class CartModel : PageModel
    {
        public List<CartDTO> Carts { get; set; }
        public string TotalPrice { get;set; }
        public string message { get;set; }
        private readonly HttpClient client = null;
        private string ApiUri = "";
        private string loginKey = "_login";


        public CartModel()
        {
            client = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);
            ApiUri = "http://localhost:5007/api/";
            //TotalPrice = 0;


        }

        public async Task<IActionResult> OnGet()
        {
            string service = "";
            string json = HttpContext.Session.GetString(loginKey) ?? "";

            var option = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
            };

            if (!Request.Query["sstore"].ToString().Equals(""))
            {
                service = Request.Query["sstore"].ToString();
            }

            if (json.Equals(""))
            {
                return RedirectToPage("Login");
            }

            AccountDTO account = JsonConvert.DeserializeObject<AccountDTO>(json);


            if (service.Equals("dequantityitem"))
            {
                int bid = Convert.ToInt32(Request.Query["idb"].ToString());
                int pid = Convert.ToInt32(Request.Query["idp"].ToString());
                //find bill item
                HttpResponseMessage response3 = await client.GetAsync(ApiUri + $"BillItem/detail/{bid}&{pid}");
                string strData3 = await response3.Content.ReadAsStringAsync();
                BillItemDTO item = System.Text.Json.JsonSerializer.Deserialize<BillItemDTO>(strData3, option);
                //find product
                HttpResponseMessage response4 = await client.GetAsync(ApiUri + $"Product/Detail/{pid}");
                string strData4 = await response4.Content.ReadAsStringAsync();
                ProductListDTO product = System.Text.Json.JsonSerializer.Deserialize<ProductListDTO>(strData4, option);
                //set item
                item.Quantity -= 1;
                item.TotalPrice -= product.Price;
                //put bill item
                string jsonitem = System.Text.Json.JsonSerializer.Serialize(item);
                StringContent content = new StringContent(jsonitem, Encoding.UTF8, "application/json");
                await client.PutAsync(ApiUri + $"BillItem/put", content);
            }

            if (service.Equals("removeitem"))
            {
                int bid = Convert.ToInt32(Request.Query["idb"].ToString());
                int pid = Convert.ToInt32(Request.Query["idp"].ToString());

                //find bill item
                HttpResponseMessage response3 = await client.GetAsync(ApiUri + $"BillItem/detail/{bid}&{pid}");
                string strData3 = await response3.Content.ReadAsStringAsync();
                BillItemDTO item = System.Text.Json.JsonSerializer.Deserialize<BillItemDTO>(strData3, option);
                //delete item
                await client.DeleteAsync(ApiUri + $"BillItem/delete/{item.BillId}&{item.ProductId}");
            }

            if (service.Equals("incquantityitem"))
            {
                int bid = Convert.ToInt32(Request.Query["idb"].ToString());
                int pid = Convert.ToInt32(Request.Query["idp"].ToString());

                //find bill item
                HttpResponseMessage response3 = await client.GetAsync(ApiUri + $"BillItem/detail/{bid}&{pid}");
                string strData3 = await response3.Content.ReadAsStringAsync();
                BillItemDTO item = System.Text.Json.JsonSerializer.Deserialize<BillItemDTO>(strData3, option);
                //find product
                HttpResponseMessage response4 = await client.GetAsync(ApiUri + $"Product/Detail/{pid}");
                string strData4 = await response4.Content.ReadAsStringAsync();
                ProductListDTO product = System.Text.Json.JsonSerializer.Deserialize<ProductListDTO>(strData4, option);
                //set item
                item.Quantity += 1;
                item.TotalPrice += product.Price;
                //put bill item
                string jsonitem = System.Text.Json.JsonSerializer.Serialize(item);
                StringContent content = new StringContent(jsonitem, Encoding.UTF8, "application/json");
                await client.PutAsync(ApiUri + $"BillItem/put", content);
            }

            HttpResponseMessage response = await client.GetAsync(ApiUri + $"BillItem/cart/{account.Id}");
            string strData = await response.Content.ReadAsStringAsync();
            Carts = System.Text.Json.JsonSerializer.Deserialize<List<CartDTO>>(strData, option);

            HttpResponseMessage response2 = await client.GetAsync(ApiUri + $"BillItem/Total/{account.Id}");
            TotalPrice = await response2.Content.ReadAsStringAsync();

            return Page();

        }

         
    }
}

SstoreClient/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace SstoreClient.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

SstoreClient/Pages/Login.cshtml.cs
using CommonLib;
using DTO.AccountDTO;
using DTO.ProductDTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Text.Json;

namespace SstoreClient.Pages
{
    public class LoginModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public List<ProductListDTO> listproduct { get; set; }
        private readonly HttpClient client = null;
        private string ApiUri = "";
        public string message { get; set; }
        private string loginKey = "_login";
        public LoginModel()
        {
            client = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);
            ApiUri = "http://localhost:5007/api/";
        }
        public async Task<IActionResult> OnGet()
        {
            //message = "kasfjasbfsjnfksgkrgnkdrgnkABC";
            HttpContext.Session.Clear();
            return Page();
        }
        
        public async Task<IActionResult> OnPostSignin()
        {

            if (Request.Form["mail"].Equals("") || Request.Form["password"].Equals(""))
            {
                message = "Please, fill all infomations";
                return Page();
            }
            else
            {
                string mail = Encryption.Instance.hashMD5(Request.Form["mail"]); 
                string password = Encryption.Instance.hashMD5(Request.Form["password"]);
                HttpResponseMessage response = await client.GetAsync(ApiUri + $"Account/authentication/{mail}&{password}");
                string strData = await response.Content.ReadAsStringAsync();

                var option = new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true,
                };

                AccountDTO acc = System.Text.Json.JsonSerializer.Deserialize<AccountDTO>(strData,option);
                if (acc != null && acc.Role == 0 && acc.Active == true)
                {
                    string json = JsonConvert.SerializeObject(acc);
                    HttpContext.Session.SetString(loginKey, json);
                    return RedirectToPage("Index");
                }

                else
                {
                    message = "Login failed";
                    return Page();
                }
            }

        }
        
        public async Task<IActionResult> OnPostSignup()
        {
            if (Request.Form["fullname"].Equals("") || Request.Form["Gender"].Equals("") ||
                Request.Form["rmail"].Equals("") || Request.Form["phone"].Equals("") ||
                Request.Form["dob"].Equals("") || Request.Form["rpassword"].Equals("") ||
                Request.Form["repassword"].Equals("") || Request.Form["address"].Equals(""))
            {
                message = "Please, fill all information!";
                return Page();
            }
            else
            {
                String fullname = Request.Form["fullname"];
                bool gender = false;
                if (Convert.ToInt32(Request.Form["Gender"]) == 1)
                {
                    gender = true;
                }
                //int gender = Convert.ToInt32(Request.Form["Gender"]);
                string mail = Request.Form["rmail"];
                string phone = Request.Form["phone"];
                DateTime dob = Convert.ToDateTime(Request.Form["dob"]);
                string address = Request.Form["address"];
                string password = Request.Form["rpassword"];
                string repass = Request.Form["repassword"];
                if (!Validate.Instance.Phone(phone))
                {
                    message = "Phone numer must 10 characters";
                    return Page();
                }

                if (!password.Equals(repass))
                {
                    message = "Password must the same repassword";
                    return Page();
                }

                if (!Validate.Instance.Mail(mail))
                {
                    message = "Email not exist";
                    return Page();
                }
                if (!Validate.Instance.Name(fullname))
                {
                    message = "Full name is Failed";
                    return Page();
                }

                string pass = Encryption.Instance.hashMD5(password);
                HttpResponseMessage response = await client.GetAsync(ApiUri + $"Account/detailmail/{mail}");
                string strData = await response.Content.ReadAsStringAsync();

                var option = new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true,
                };

                AccountDTO acc = System.Text.Json.JsonSerializer.Deserialize<AccountDTO>(strData, option);

                if (acc.Id == 0)
                {
                    
                   AccountAddDTO a = new AccountAddDTO
                    {
                        FullName = fullname,
                        Email = mail,
                        Address = address,
                        Dob = dob,
                        Gender = gender,
                        Phone = phone,
                        Password = pass,
                        Active = false,
                        Role = 0

                    };

                    string jar = JsonConvert.SerializeObject(a);
                    string otp = SendMail.Instance.GetOTP();

                    HttpContext.Session.SetString("jar",jar);
                    HttpContext.Session.SetString("otp",otp);

                    try
                    {
                       SendMail.Instance.Send(mail, otp, "S Store active account");
                    }catch(Exception ex)
                    {
                        message = "Email does not exist!";
                      
                    }

                    return RedirectToPage("CheckOTP");
                }
                else
                {
                     message = "Email register exist, try again";
                 
                    return Page();
                }
            }

        }
        
    }
}

SstoreClient/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SstoreClient.Pages
{
    public class LogoutModel : PageModel
    {
        public async Task<IActionResult> OnGet()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("Index");
        }
    }
}

SstoreClient/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SstoreClient.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

SstoreClient/Pages/Shared/Checkout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SstoreClient.Pages.Shared
{
    public class CheckoutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SstoreClient/Pages/Shop.cshtml.cs
using DTO.AccountDTO;
using DTO.CategoryDTO;
using DTO.ProductDTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using SstoreClient.ModelTMP;
using System.Collections;
using System.Net.Http.Headers;
using System.Text.Json;

namespace SstoreClient.Pages
{
    public class ShopModel : PageModel
    {
        private readonly HttpClient client = null;
        private string ApiUri = "";
        public string message { get; set; }
        public List<CategoryDTO> listcategory { get; set; }
        public List<ProductListDTO> productlist { get; set; }
        private static string category = "";
        private static string fproductname = "";
        private string loginKey = "_login";
        private string cartKey = "_cart";

        public ShopModel()
        {
            client = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);
            ApiUri = "http://localhost:5007/api/";
        }

        public async Task<IActionResult> OnGet()
        {
             string service = "";
             category = Request.Query["categoryid"].ToString();

            var option = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
            };

            if (!Request.Query["sstore"].ToString().Equals(""))
            {
                service = Request.Query["sstore"].ToString();
            }

            if (category.Equals(""))
            {
                category = "null";
            }

            if (fproductname.Equals(""))
            {
                fproductname = "null";
            }

            if (service.Equals("AddToCart"))
            {

                string json = HttpContext.Session.GetString(loginKey) ?? "";
                int productid = Convert.ToInt32(Request.Query["productid"]);
                int quantity = Convert.ToInt32(Request.Query["quantity"]);

                //case user login page
                if (!json.Equals(""))
                {
                    AccountDTO account = JsonConvert.DeserializeObject<AccountDTO>(json);
                    //add to cart
                    await client.GetAsync(ApiUri + $"Shoping/addtocart/{account.Id}&{productid}&{quantity}");
                }
                else
                {
                    return RedirectToPage("Login");
                }
                
                
            }

            HttpResponseMessage response = await client.GetAsync(ApiUri + $"Product/list/{category}&null");
            HttpResponseMessage response2 = await client.GetAsync(ApiUri + $"Category/list/null");
            string strData = await response.Content.ReadAsStringAsync();
            string strData2 = await response2.Content.ReadAsStringAsync();

            listcategory = System.Text.Json.JsonSerializer.Deserialize<List<CategoryDTO>>(strData2, option);
            productlist = System.Text.Json.JsonSerializer.Deserialize<List<ProductListDTO>>(strData, option);
            return Page();
        }

        public async Task<IActionResult> OnPostFillter()
        {
             fproductname = Request.Form["nameproduct"];

            if (fproductname.Equals(""))
            {
                fproductname = "null";
            }

            HttpResponseMessage response = await client.GetAsync(ApiUri + $"Product/list/{category}&{fproductname}");
            HttpResponseMessage response2 = await client.GetAsync(ApiUri + $"Category/list/null");
            string strData = await response.Content.ReadAsStringAsync();
            string strData2 = await response2.Content.ReadAsStringAsync();

            var option = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
            };

            listcategory = System.Text.Json.JsonSerializer.Deserialize<List<CategoryDTO>>(strData2, option);
            productlist = System.Text.Json.JsonSerializer.Deserialize<List<ProductListDTO>>(strData, option);

            return Page();
        }


       
    }
}

SstoreClient/Pages/Cart.cshtml
@page
@model SstoreClient.Pages.CartModel
@{
}
<section class="shoping-cart spad">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="shoping__cart__table">
                             <p style="color:Tomato;">@Model.message</p>
                            <table>
                                <thead>
                                    <tr>
                                        <th class="shoping__product">Products</th>
                                        <th>Price</th>
                                        <th>Quantity</th>
                                        <th>Total</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.Carts) {
                                         <tr>
                                            <td class="shoping__cart__item">
                                                <img src="image/@item.Image" alt="">
                                                <h5 name = "proname">@item.ProductName</h5>
                                            </td>
                                            <td class="shoping__cart__price">
                                                @item.Price VND
                                            </td>
                                            <td class="shoping__cart__quantity">
                                                <div class="quantity">
                                                    <div > 
                                                        @if(item.Quantity>1)
                                                        {
                                                        <a href="Cart?sstore=dequantityitem&idb=@item.BillId&idp=@item.ProductId" style="color:black; font-size:20px;">-</a>
                                                        }

                                                        @if (item.Quantity == 1)
                                                         {
                                                        <a href="Cart?sstore=removeitem&idb=@item.BillId&idp=@item.ProductId" style="color:black; font-size:20px;">-</a>
                                                          }
                                                     @item.Quantity
                                                        <a href="Cart?sstore=incquantityitem&idb=@item.BillId&idp=@item.ProductId" style="color:black; font-size:20px;">+</a>
                                                    </div>
                                                </div>
                                            </td>
                                            <td class="shoping__cart__total">
                                                 @item.TotalPrice VND
                                            </td>
                                            <td class="shoping__cart__price">
                                                 <a href="Cart?sstore=removeitem&idb=@item.BillId&idp=@item.ProductId" style="color:Tomato;" class="breadcrumb__option">X</a>
                                            </td>
                                        </tr>  
                                        }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="shoping__cart__btns">
                            <a asp-page="/PurchaseOrder" class="primary-btn cart-btn">PURCHASE ORDER</a>
                        </div>
                    </div>
                    <div class="col-lg-6">

                    </div>
                    <div class="col-lg-6">
                        <div class="shoping__checkout">
                            <h5>Cart Total</h5>
                            <ul>
                                <li>Total <span>@Model.TotalPrice VND</span></li>
                            </ul>
                            <a asp-page="/Checkout" class="primary-btn">PROCEED TO CHECKOUT</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Shoping Cart Section End -->

SstoreClient/Pages/CheckOTP.cshtml
@page
@model SstoreClient.Pages.CheckOTPModel
@{
    ViewData["Title"] = "Check OTP";
}
<div class="login-wrap">
            <div class="login-html">
                  <p style="color:Tomato;">@Model.message</p>
                <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab"></label>
                <input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab"></label>
                <div class="login-form" >
                    <form method="post">
                        <div class="sign-in-htm">
                            <div class="group">
                                <label for="user" class="label">OTP</label>
                                <input id="user" type="text" class="input" name = "otp">
                            </div>
                            <div class="group">
                                <input type="submit" class="button" value="Submit" name="submit">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

SstoreClient/Pages/GetOTP.cshtml
@page
@model SstoreClient.Pages.GetOTPModel
@{
}

SstoreClient/Pages/Login.cshtml
@page
@model SstoreClient.Pages.LoginModel
@{
    ViewData["Title"] = "Login";
}
<div class="login-wrap">
    <p style="color:Tomato;">@Model.message</p>
            <div class="login-html">
                <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Login</label>
                <input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Register</label>
                <div class="login-form">

                    <form asp-page-handler="Signin" method="post">
                        <div class="sign-in-htm">
                            <div class="group">
                                <label for="user" class="label">Email</label>
                                <input id="user" type="text" class="input" name ="mail">
                            </div>
                            <div class="group">
                                <label for="pass" class="label">Password</label>
                                <input id="pass" type="password" class="input" data-type="password" name = "password">
                            </div>
                            <div class="group">
                                <input type="submit" class="button" value="SignIn">
                            </div>
                            <div class="hr"></div>
                            <div class="foot-lnk">
                                <a asp-page="/MailForgotPassword">Forgot Password?</a>
                            </div>
                        </div>
                    </form>
                    
                    <form asp-page-handler="Signup" method="post">
                        <div class="sign-up-htm">
                            <div class="group">
                                <label for="user" class="label">Full Name</label>
                                <input id="user" type="text" class="input" name ="fullname">
                            </div>
                            <div class="group">
                                <label for="user" class="label">Gender</label>
                                   <select name="Gender" class="label">
                                      <option id="user" value="0">Male</option>
                                      <option id="user" value="1">Female</option>
                                   </select>
                            </div>
                            <div class="group">
                                <label for="pass" class="label">Email</label>
                                <input id="pass" type="email" class="input" name="rmail">
                            </div>
                            <div class="group">
                                <label for="pass" class="label">Phone</label>
                                <input id="pass" type="text" class="input" name="phone">
                            </div>
                            <div class="group">
                                <label for="user" class="label">Date Of Birth</label>
                                <input id="user" type="date" class="input" name ="dob">
                            </div>
                            <div class="group">
                                <label for="pass" class="label">Address</label>
                                <input id="pass" type="text" class="input" name="address">
                            </div>
                            <div class="group">
                                <label for="pass" class="label">Password</label>
                                <input id="pass" type="password" class="input" data-type="password" name ="rpassword">
                            </div>
                            <div class="group">
                                <label for="pass" class="label">Repeat Password</label>
                                <input id="pass" type="password" class="input" data-type="password" name="repassword">
                            </div>
                            <div class="group">
                                    <input type="submit" class="button" value="SignUp" name="submit">
                            </div>
                            <div class="hr"></div>
                            <div class="foot-lnk">
                                <label for="tab-1">Already Member?</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

SstoreClient/Pages/Shop.cshtml
@page
@model SstoreClient.Pages.ShopModel
@{
    ViewData["Title"] = "Shop";
}
<div id="preloder">
            <div class="loader"></div>
        </div>

        <!-- Hero Section Begin -->
        <section class="hero hero-normal">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="hero__categories">
                            <div class="hero__categories__all">
                                <i class="fa fa-bars"></i>
                                <span>All Categorires</span>
                            </div>
                            
                                <ul>
                                    @foreach (var item in Model.listcategory) {
                                        <li><a asp-page="Shop" asp-route-categoryid="@item.Id">@item.CategoryName</a></li>
                                    }
                                     <li><a asp-page="Shop" asp-route-categoryid="">All categories</a></li>
                                </ul>
                        </div>
                    </div>
                    <div class="col-lg-9">
                        <div class="hero__search">
                            <div class="hero__search__form">
                                <form asp-page-handler="Fillter" method = "post">
                                    <div class="hero__search__categories">
                                        All Categories
                                        <span class="arrow_carrot-down"></span>
                                    </div>
                                    <input type="text" placeholder="What do you need?" name="nameproduct">
                                    <button type="submit" class="site-btn">SEARCH</button>
                                </form>
                            </div>
                            <div class="hero__search__phone">
                                <div class="hero__search__phone__icon">
                                    <i class="fa fa-phone"></i>
                                </div>
                                <div class="hero__search__phone__text">
                                    <h5>0917076864</h5>
                                    <span>support 24/7 time</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="featured spad">
            <div class="container">
                    <div class="row featured__filter" >
                        @foreach (var item in Model.productlist) {
                    @if (item.Quantity > 0)
                    {
                        <div class="col-lg-3 col-md-4 col-sm-6 mix fastfood vegetables">
                            <div class="featured__item">
                                <div class="featured__item__pic set-bg" data-setbg="image/@item.Image">
                                    <ul class="featured__item__pic__hover"> 
                                        <li><a href="Shop?sstore=AddToCart&productid=@item.Id&quantity=1"><i class="fa fa-shopping-cart"></i></a></li>
                                    </ul>
                                </div>
                                <div class="featured__item__text">
                                    <h6><a href="ProductDetail?idp=@item.Id">@item.ProductName</a></h6>
                                    <h5>@item.Price VND</h5>
                                </div>
                            </div>
                        </div>
                    }
                }
                    </div>
            </div>
        </section>